// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Cutter = (function(_super) {

    __extends(Cutter, _super);

    function Cutter() {
      this._onCropChange = __bind(this._onCropChange, this);

      this._onShowoffUpdate = __bind(this._onShowoffUpdate, this);
      return Cutter.__super__.constructor.apply(this, arguments);
    }

    Cutter.prototype.settings = {
      onNoBrowserSupport: null,
      aspectRatio: null,
      geometryFields: {
        x: null,
        y: null,
        w: null,
        h: null
      }
    };

    Cutter.prototype.jCrop = null;

    Cutter.prototype.$img = null;

    Cutter.prototype.$container = null;

    Cutter.prototype.initialize = function(options) {
      var _this = this;
      this.options = $.extend({}, this.settings, options);
      delete this.options.el;
      this.$container = this.$(".js-image_container");
      this.$img = this.$(".js-image");
      return this.$("input[type=file]").showoff({
        destination: this.$img,
        onNoBrowserSupport: function() {
          if (_this.options.onNoBrowserSupport) {
            return _this.options.onNoBrowserSupport();
          }
        },
        onDestinationUpdate: this._onShowoffUpdate
      });
    };

    Cutter.prototype._onShowoffUpdate = function() {
      var jcropOptions, that;
      if (this.jCrop != null) {
        this.jCrop.destroy();
        this.$img.removeAttr("style");
      }
      this.$container.show();
      jcropOptions = {
        onChange: this._onCropChange,
        onSelect: this._onCropChange
      };
      if (this.options.aspectRatio) {
        jcropOptions.aspectRatio = this.options.aspectRatio;
        jcropOptions.setSelect = [0, 0, this.$img.width()];
      }
      that = this;
      return this.$img.Jcrop(jcropOptions, function() {
        return that.jCrop = this;
      });
    };

    Cutter.prototype._onCropChange = function(event) {
      var $el, coord, height, relativeCoords, width, _ref, _results;
      width = this.$img.width();
      height = this.$img.height();
      relativeCoords = {
        w: event.w / width,
        h: event.h / height,
        x: event.x / width,
        y: event.y / height
      };
      _ref = this.options.geometryFields;
      _results = [];
      for (coord in _ref) {
        $el = _ref[coord];
        _results.push($el.val(relativeCoords[coord]));
      }
      return _results;
    };

    return Cutter;

  })(Backbone.View);

}).call(this);
